### ISSUE TITLE
has no member named ‘getIdentityPose’ 

### ISSUE THREAD

**Issue by CesMak** [ros-planning/moveit_grasps#92]
Hey there,

- Ubuntu 18.04
- Melodic

building moveit_grasps fails for me with this error:

```
Errors     << moveit_grasps:make /home/mlamprecht/Desktop/melodic_ws/logs/moveit_grasps/build.make.003.log                                 
In file included from /home/mlamprecht/Desktop/melodic_ws/src/moveit_grasps/src/demo/grasp_generator_demo.cpp:46:0:
/home/mlamprecht/Desktop/melodic_ws/src/moveit_grasps/include/moveit_grasps/grasp_generator.h: In member function ‘void moveit_grasps::GraspGenerator::setIdealGraspPoseRPY(const std::vector<double>&)’:
/home/mlamprecht/Desktop/melodic_ws/src/moveit_grasps/include/moveit_grasps/grasp_generator.h:426:53: warning: ‘void moveit_grasps::GraspGenerator::setIdealGraspPoseRPY(const std::vector<double>&)’ is deprecated: setIdealGraspPoseRPY has been renamed to setIdealTCPGraspPoseRPY [-Wdeprecated-declarations]
     setIdealGraspPoseRPY(ideal_grasp_orientation_rpy);
                                                     ^
/home/mlamprecht/Desktop/melodic_ws/src/moveit_grasps/include/moveit_grasps/grasp_generator.h:424:3: note: declared here
   setIdealGraspPoseRPY(const std::vector<double>& ideal_grasp_orientation_rpy)
   ^~~~~~~~~~~~~~~~~~~~
/home/mlamprecht/Desktop/melodic_ws/src/moveit_grasps/src/demo/grasp_generator_demo.cpp: In constructor ‘moveit_grasps::GraspGeneratorDemo::GraspGeneratorDemo(int)’:
/home/mlamprecht/Desktop/melodic_ws/src/moveit_grasps/src/demo/grasp_generator_demo.cpp:156:49: error: ‘using element_type = class moveit_visual_tools::MoveItVisualTools {aka class moveit_visual_tools::MoveItVisualTools}’ has no member named ‘getIdentityPose’
       geometry_msgs::Pose pose = visual_tools_->getIdentityPose();
```

Any ideas what is going wrong here?

**Comment by Dale-Koenig** [comment]
Use `melodic-devel` for MoveitVisualTools and it should fix the problem.  The melodic branches of various moveit repos should work together, and the master branches should all work together, but mixing and matching isn't guaranteed to work.

**Comment by karolyartur** [comment]
Hi!

- OS Version: Ubuntu 18.04.4 LTS
- ROS Distro: Melodic

The same error appears for me as well, when I try to build moveit_grasps from source, even though I am on the `melodic-devel` branch of both moveit_grasps and MoveitVisualTools.

I also tried with using the master branches for both, but I get the same error.

**Comment by Dale-Koenig** [comment]
Apologies, it is `rviz_visual_tools`, not `moveit_visual_tools` that matters.

**Comment by karolyartur** [comment]
I tried building `moveit_grasps` again while all three (`moveit_grasps`, `rviz_visual_tools` and `moveit_visual_tools`) packages are at their `melodic-devel` branch, but I still get the same error.

On `rviz_visual_tools` I am at commit 0c78ae2c (3.8.0 release)
On `moveit_visual_tools` at commit f6388b
and on `moveit_grasps` at bdbc78

I also tried with all the packages at `master` branch, but it still gives the same error.

**Comment by Dale-Koenig** [comment]
It seems `getIdentityPose` was added to `rviz_visual_tools` right after the 3.8.0 release, so perhaps the change to use that function should not have been applied to melodic_devel of `moveit_grasps`.  So at the moment, it may be best to have `rviz_visual_tools` on the master branch even with `melodic` build of `moveit_grasps`.

However, with both on `master` branch it works (and builds successfully in CI).  It is possible you are somehow not linking to the right copy of `rviz_visual_tools`, i.e. perhaps you are linking to the version in your ros install instead of the version built from source.

**Comment by karolyartur** [comment]
Thank you!

Using the `master` branch of `rviz_visual_tools` and the `melodic-devel` branch of `moveit_grasps` works for me.

**Comment by Reaper151** [comment]
I already use `master` branch of `rviz_visual_tools` and the `melodic-devel` branch of `moveit_grasps` as this reply but I still get this error.
PS. my 'rviz_visual_tools' is 3.8.0-4bionic.20200320.161551 and moveit_grasps is from zip file of melodic-devel


> Thank you!
> 
> Using the `master` branch of `rviz_visual_tools` and the `melodic-devel` branch of `moveit_grasps` works for me.

**Comment by cedre26** [comment]
Hello! I have been running in the exact same problem. However, I am new to ROS and I do not understand how to link to the source version instead of the one installed in `/opt/ros`. If changes are necessary in the `CMakeLists`, what should they be?

> perhaps you are linking to the version in your ros install instead of the version built from source.

**Comment by Dale-Koenig** [comment]
> I already use `master` branch of `rviz_visual_tools` and the `melodic-devel` branch of `moveit_grasps` as this reply but I still get this error.
> PS. my 'rviz_visual_tools' is 3.8.0-4bionic.20200320.161551 and moveit_grasps is from zip file of melodic-devel
> 
> > Thank you!
> > Using the `master` branch of `rviz_visual_tools` and the `melodic-devel` branch of `moveit_grasps` works for me.

You may have to use both rviz_visual_tools and moveit_visual_tools from source, since if you only use the former from source, the latter will still reference the released version of rviz_visual_tools.

**Comment by ZinnerC** [comment]
Hello. I currently have the same problem.
I use the following build from source:
- moveit_visual_tools (melodic-devel)
- rviz_visual_tools (master)
- moveit_grasps (master) 

If I do "catkin build moveit_graps", the following packages get built (panda_moveit_config, rviz_visual_tools, moveit_visual_tools, moveit_grasps) during the build of "moveit_grasps" i get the error "has no member named ‘getIdentityPose' "

Same error occures also for moveit_grasps on melodic-devel of the rest stays the same.

If I switch with moveit_visual_tools to melodic_devel the single build does not even work. Giving the error ‘solidPrimitiveDimCount’ is not a member of ‘geometric_shapes’

What was the solution for the other before me?
Thanks for you help.

**Comment by felixvd** [comment]
Are you building the rest of MoveIt from source as well?

**Comment by ZinnerC** [comment]
Hello felixvd.
No I used "sudo apt install ros-melodic-moveit".
Should I? And if yes which branch should I use to build it from source?
Thanks for you help.

**Comment by ZinnerC** [comment]
So for everybody who will have a similar issue. the following repositories on the respecitve branches worked to build "moveit_grasps"

- moveit (melodic-devel)
- moveit_msgs (melodic-devel)
- moveit_grasps (melodic-devel)
- moveit_visual_tools (melodic-devel)
- rviz_visual_tools (master)
- geometric_shapes (melodic-devel)

**Comment by Tuebel** [comment]
I ran into this issue, too. Indeed, building moveit from source was the key to success. Right now using `melodic-devel` for all the packages seems to work.

Make sure to uninstall `ros-melodic-moveit` from your system to prevent linking to the wrong version.

**Comment by felixvd** [comment]
> So for everybody who will have a similar issue. the following repositories on the respecitve branches worked to build "moveit_grasps"

Sorry for the late response. If you follow the [build instructions](https://moveit.ros.org/install/source/), those dependencies are cloned into your workspace automatically using `wstool` and the `.rosinstall` file.

Also, you don't need to uninstall `ros-melodic-moveit` from your system to use moveit as built from source. Just make sure to source your workspace's `setup.bash` (`cd your_catkin_ws && source devel/setup.bash`) and check with `rospack list | grep moveit` that the links point to your workspace and not `/opt/ros/...`.
